### ISSUE TITLE
lightgbm v4.0.0?

### ISSUE THREAD

**Issue by kdarby-cqg** [StatMixedML/LightGBMLSS#25]
Hi, I'm trying your package since you added normflows, could you please upgrade the gbm to v4.0.0?

I think they removed the `fobj` param from the train() function, and you'd have specify in params

Thanks!

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lightgbmlss 0.3.0 requires lightgbm~=3.3.5, but you have lightgbm 4.0.0 which is incompatible.

> ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:2                                                                                    │
│                                                                                                  │
│   1 # Train Model with optimized hyperparameters                                                 │
│ ❱ 2 lss_model = lgblss.train(lss_params,                                                         │
│   3 │   │   │   │   │   │    lgbtrain,                                                           │
│   4 │   │   │   │   │   │    num_boost_round=lss_params['num_boost_round'],                      │
│   5 │   │   │   )                                                                                │
│                                                                                                  │
│ /home/algo/code/cqg/bts/spark/ml/.venv/lib/python3.9/site-packages/lightgbmlss/model.py:178 in   │
│ train                                                                                            │
│                                                                                                  │
│   175 │   │   if valid_sets is not None:                                                         │
│   176 │   │   │   valid_sets = self.set_valid_margin(valid_sets, self.start_values)              │
│   177 │   │                                                                                      │
│ ❱ 178 │   │   self.booster = lgb.train(params,                                                   │
│   179 │   │   │   │   │   │   │   │    train_set,                                                │
│   180 │   │   │   │   │   │   │   │    num_boost_round=num_boost_round,                          │
│   181 │   │   │   │   │   │   │   │    fobj=self.dist.objective_fn,                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: train() got an unexpected keyword argument 'fobj'

**Comment by kdarby-cqg** [comment]
> https://lightgbm.readthedocs.io/en/v4.0.0/pythonapi/lightgbm.train.html

**Comment by StatMixedML** [comment]
Thanks for your interest in the package. Right now I am not planning to upgrade to the latest LightGBM release. So please install the package in a fresh environment with the specified package dependencies.Thanks !Am 04.08.2023 um 18:36 schrieb kdarby-cqg ***@***.***>:﻿
Hi, I'm trying your package since you added normflows, could you please upgrade the gbm to v4.0.0?
I think they removed the fobj param from the train() function, and you'd have specify in params
Thanks!

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lightgbmlss 0.3.0 requires lightgbm~=3.3.5, but you have lightgbm 4.0.0 which is incompatible.


╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in :2                                                                                    │
│                                                                                                  │
│   1 # Train Model with optimized hyperparameters                                                 │
│ ❱ 2 lss_model = lgblss.train(lss_params,                                                         │
│   3 │   │   │   │   │   │    lgbtrain,                                                           │
│   4 │   │   │   │   │   │    num_boost_round=lss_params['num_boost_round'],                      │
│   5 │   │   │   )                                                                                │
│                                                                                                  │
│ /home/algo/code/cqg/bts/spark/ml/.venv/lib/python3.9/site-packages/lightgbmlss/model.py:178 in   │
│ train                                                                                            │
│                                                                                                  │
│   175 │   │   if valid_sets is not None:                                                         │
│   176 │   │   │   valid_sets = self.set_valid_margin(valid_sets, self.start_values)              │
│   177 │   │                                                                                      │
│ ❱ 178 │   │   self.booster = lgb.train(params,                                                   │
│   179 │   │   │   │   │   │   │   │    train_set,                                                │
│   180 │   │   │   │   │   │   │   │    num_boost_round=num_boost_round,                          │
│   181 │   │   │   │   │   │   │   │    fobj=self.dist.objective_fn,                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: train() got an unexpected keyword argument 'fobj'

**Comment by StatMixedML** [comment]
I am closing this for now. Future releases will include upgrading to the latest version.
